name: Security

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 11 * * 2'
    
jobs:
  dockerscan:
    name: Docker Scan
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v1
      - 
        name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      -
         name: Docker login
         env:
           USER: hazcod
           REGISTRY: docker.pkg.github.com/ironpeakservices/iron-redis
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${USER}" --password-stdin "${REGISTRY}"
      - 
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.pkg.github.com/ironpeakservices/iron-redis/iron-redis:${{ env.RELEASE_VERSION }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
      - 
        name: Upload Trivy scan results to Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
