name: Security

on:
  push:
    branches: [master, ]
  pull_request:
  schedule:
    - cron: '0 11 * * 2'
    
jobs:
  dockerscan:
    name: Scan
    runs-on: ubuntu-latest
    needs: dockerbuild
    steps:
    - uses: actions/checkout@v2.0.0
    - name: extract tag
      id: vars
      run: echo ::set-output name=redis_version::$(grep '^FROM redis' Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
    - name: load cached docker image
      uses: actions/cache@v2
      with:
        path: image/
        key: ${{ runner.os }}-docker-${{ github.sha }}
    - name: load cached docker container
      run: docker load -i image/image.tar
    - name: cached scan db
      uses: actions/cache@v2
      with:
        path: vulndb/
        key: trivy-vulndb
    - name: Install Trivy
      run:  |
        trivyRelease="$(curl -s "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -d 'v' -f 2)"
        wget https://github.com/aquasecurity/trivy/releases/download/v${trivyRelease}/trivy_${trivyRelease}_Linux-64bit.tar.gz
        tar zxvf trivy_${trivyRelease}_Linux-64bit.tar.gz
        curl -O sarif.tpl https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/sarif.tpl
    - name: Scan
      run: |
        ./trivy --no-progress \
          --severity HIGH,CRITICAL,MEDIUM \
          --cache-dir vulndb/ \
          --format template --template sarif.tpl -o results.sarif \
          image:${{ steps.vars.outputs.redis_version }}
    - name: Upload Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
